[project]
name = "luna-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "datasets>=4.4.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
